### ISSUE TITLE
La descompresión no genera el mismo archivo original

### ISSUE THREAD

**Issue by fabro-08** [ArielCaballero/Compresor-LZW-Huffman-Dinamico#1]
Buenísimo! Se siguió la consigna deseada, y corre el compresor y descompresor sin embargo se probo con un texto ejemplo que se repitio varias veces y la salida de la descompresión no fue igual al archivo origen.
Esta muy bien encaminado el desarrollo. Dejo el ejemplo que probé para que puedas revisar donde esta el problema

[ejemplo.txt](https://github.com/user-attachments/files/17468651/ejemplo.txt)

Saludos!

**Comment by ArielCaballero** [comment]
Se solucionó el problema que había en la compresión LZW. Probé con varias cadenas mas largas y repeticiones de la misma, sigue comprimiendo lento archivos de  tamaño cerca del MB, pero comprime distintos tipos de extensiones.

**Comment by fabro-08** [comment]
Excelente Ariel buen trabajo!
Cierro el Issue.
